# Theme version
editorial:        "1.0"

# Header Elements
favicon:          /favicon.png

# Sidebar Widgets
# Those widgets reside in /layout/partial/sidebar/
# Their control code is in /layout/partial/sidebar.ejs
widgets:
  search:         true
  menu:           true
  articles:       true
  getintouch:     true
  footer:         true

# Widgets Configuration

## Menu Widget
menu:
  title:          Menu
  items:
    Home:         /
    About Ahmed:  /about/
    Contact Me:   /contact/
    Archives:     /archives/

## Contact Widget
contact:
  title:          Drop me a message
  message:        Don't hesitate to drop me a message. Seriously. I reply to all of them. 🤷‍♂️
  email:          hi@nef.im
  phone:          (00216) 99 999 999
  address:        Certain place in the world<br/>Not here.

## Footer Widget
footer:           Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/anefzaoui/Editorial-Hexo" target="_blank">Editorial</a>


# Social media links
twitter_url:      https://twitter.com/AhmedNefzaoui
facebook_url:     https://facebook.com/anefzaoui1
snapchat_url:
instagram_url:
medium_url:
google_plus_url:

# Analytics
google_analytics:
fb_admins:
fb_app_id:
